spring:
    thymeleaf:
      mode: HTML5
      cache: false
    resources:
      cache-period: 0
    datasource:
      url: jdbc:postgresql://localhost:5432/vibe
      username: vibe
      password: vibe
    rabbitmq:
      host: localhost
      username: guest
      password: guest